version: '3'
services:
  app:
    build: .
    image: ${DOCKER_USER_ID}/ubuntu_flask
  production:
    image: ${DOCKER_USER_ID}/ubuntu_flask:57
    volumes: 
      - .:/code
    command: python3 app.py
    ports:
      - "5000:5000"
